import streamlit as st
from google import genai
from pypdf import PdfReader
import base64

# -----------------------------
# PAGE SETTINGS
# -----------------------------
st.set_page_config(
    page_title="ASH Study Assistant",
    page_icon="logo.png",
    layout="centered"
)

# -----------------------------
# GEMINI CONNECTION
# -----------------------------
client = genai.Client(api_key=st.secrets["GEMINI_API_KEY"])

# -----------------------------
# TITLE
# -----------------------------
st.image("logo.png", width=150)
st.title("ASH Study Assistant")
st.write("Ask me anything about your studies!")

# -----------------------------
# PDF UPLOAD
# -----------------------------
st.sidebar.header("📄 Study Material")

uploaded_file = st.sidebar.file_uploader(
    "Upload your university notes (PDF)",
    type=["pdf"]
)

pdf_text = ""

if uploaded_file is not None:

    pdf_reader = PdfReader(uploaded_file)

    for page in pdf_reader.pages:
        text = page.extract_text()

        if text:
            pdf_text += text + "\n"

    st.sidebar.success(
        f"✅ PDF loaded! {len(pdf_reader.pages)} pages found."
    )

# -----------------------------
# STUDY MODE
# -----------------------------
mode = st.selectbox(
    "Choose Study Mode",
    [
        "💬 Normal Chat",
        "📚 Explain Topic",
        "📝 Make Notes",
        "❓ Generate MCQs",
        "🎯 Exam Questions",
        "🎨 Generate Image"
    ]
)

# ============================================================
# IMAGE GENERATOR
# ============================================================

if mode == "🎨 Generate Image":

    st.header("🎨 AI Image Generator")

    st.write(
        "Describe the image you want. "
        "For example: create a diagram explaining the water cycle."
    )

    image_prompt = st.text_area(
        "Describe your image",
        placeholder=(
            "Example: Create a simple educational diagram "
            "showing the water cycle with evaporation, "
            "condensation, precipitation and collection."
        ),
        height=120
    )

    # Image generation button
    if st.button("🎨 Generate Image", use_container_width=True):

        if not image_prompt.strip():

            st.warning("Please describe the image you want.")

        else:

            with st.spinner("Creating your image..."):

                try:

                    # Gemini image generation
                    response = client.models.generate_content(
                        model="gemini-3.1-flash-image",
                        contents=image_prompt
                    )

                    image_found = False

                    # Look through the response for generated image data
                    if response.candidates:

                        for candidate in response.candidates:

                            if not candidate.content:
                                continue

                            for part in candidate.content.parts:

                                # Generated image
                                if hasattr(part, "inline_data") and part.inline_data:

                                    image_data = part.inline_data.data

                                    # Handle bytes or base64 data
                                    if isinstance(image_data, str):
                                        image_bytes = base64.b64decode(
                                            image_data
                                        )
                                    else:
                                        image_bytes = image_data

                                    st.image(
                                        image_bytes,
                                        caption="Generated by ASH Study Assistant",
                                        use_container_width=True
                                    )

                                    st.download_button(
                                        "⬇️ Download Image",
                                        data=image_bytes,
                                        file_name="ash_study_image.png",
                                        mime="image/png",
                                        use_container_width=True
                                    )

                                    image_found = True
                                    break

                            if image_found:
                                break

                    if not image_found:

                        st.error(
                            "The image model did not return an image. "
                            "Your Gemini API account may not have access "
                            "to this image-generation model."
                        )

                except Exception as e:

                    st.error("Image generation failed.")

                    st.code(str(e))

                    st.info(
                        "If you see a model availability or API access "
                        "error here, send me the error and I'll help you "
                        "fix it."
                    )

# ============================================================
# NORMAL STUDY CHAT
# ============================================================

else:

    # -----------------------------
    # CHAT HISTORY
    # -----------------------------
    if "messages" not in st.session_state:
        st.session_state.messages = []

    for message in st.session_state.messages:

        with st.chat_message(message["role"]):
            st.markdown(message["content"])

# -----------------------------
# TEXT INPUT
# -----------------------------
typed_prompt = st.chat_input("Ask your study question...")

# -----------------------------
# VOICE INPUT
# -----------------------------
audio_value = st.audio_input(
    "🎤 Or record your question"
)

voice_prompt = None

if audio_value is not None:

    with st.spinner("🎧 Understanding your voice..."):

        try:
            audio_file = client.files.upload(
                file=audio_value
            )

            response = client.models.generate_content(
                model="gemini-3.7-flash",
                contents=[
                    audio_file,
                    "Convert the student's spoken question into text. "
                    "Return ONLY the question. Do not answer it."
                ]
            )

            voice_prompt = response.text.strip()

            st.success("🎤 Voice question:")
            st.write(voice_prompt)

        except Exception as e:
            st.error("Could not understand the voice recording.")
            st.code(str(e))

# Use either typed question OR voice question
prompt = typed_prompt

if voice_prompt:
    prompt = voice_prompt

    if prompt:

        st.session_state.messages.append(
            {"role": "user", "content": prompt}
        )

        with st.chat_message("user"):
            st.markdown(prompt)

        # -----------------------------
        # STUDY MODE INSTRUCTIONS
        # -----------------------------
        instructions = {

            "💬 Normal Chat":
                "Answer the student's question clearly and accurately.",

            "📚 Explain Topic":
                "Explain the topic in extremely simple words. "
                "Use examples and step-by-step explanations.",

            "📝 Make Notes":
                "Convert the student's topic into short, "
                "easy-to-revise study notes with headings "
                "and bullet points.",

            "❓ Generate MCQs":
                "Create 10 important multiple-choice questions. "
                "Give four options and clearly identify the correct answer.",

            "🎯 Exam Questions":
                "Create important exam-style questions from this topic. "
                "Include both short and long questions."
        }

        # -----------------------------
        # PDF INSTRUCTIONS
        # -----------------------------
        if pdf_text:

            pdf_instructions = f"""
The student has uploaded university study material.

IMPORTANT:
- Use the uploaded PDF as the main source for your answer.
- Answer the student's question based on the PDF.
- If the answer is not available in the PDF, clearly say:
  "I couldn't find this information in your uploaded PDF."
- Do not invent information and pretend it came from the PDF.

UPLOADED PDF CONTENT:
--------------------
{pdf_text}
--------------------
"""

        else:

            pdf_instructions = """
No PDF has been uploaded.

Answer the student's question using your normal knowledge.
"""

        # -----------------------------
        # SYSTEM PROMPT
        # -----------------------------
        system_prompt = f"""
You are an AI Study Assistant.

Your goal is to help university students learn.

Study mode:
{instructions[mode]}

Rules:
- Use simple English.
- Explain difficult concepts step by step.
- Give examples whenever useful.
- Do not unnecessarily use complicated terminology.
- If the student asks for an exam answer, make it easy to memorize.

{pdf_instructions}
"""

        # -----------------------------
        # AI RESPONSE
        # -----------------------------
        with st.chat_message("assistant"):

            with st.spinner("Thinking..."):

                response = client.models.generate_content(
                    model="gemini-3.6-flash",
                    contents=(
                        system_prompt
                        + "\n\nStudent question:\n"
                        + prompt
                    )
                )

                answer = response.text

                st.markdown(answer)

        # -----------------------------
        # SAVE AI RESPONSE
        # -----------------------------
        st.session_state.messages.append(
            {"role": "assistant", "content": answer}
        )
