```python
import streamlit as st
from google import genai
from pypdf import PdfReader
from huggingface_hub import InferenceClient
from io import BytesIO

# -----------------------------
# PAGE SETTINGS
# -----------------------------
st.set_page_config(
    page_title="ASH Study Assistant",
    page_icon="logo.png",
    layout="centered"
)

# -----------------------------
# GEMINI CONNECTION
# -----------------------------
client = genai.Client(
    api_key=st.secrets["GEMINI_API_KEY"]
)

# -----------------------------
# HUGGING FACE CONNECTION
# -----------------------------
image_client = InferenceClient(
    api_key=st.secrets["HF_TOKEN"]
)

# -----------------------------
# TITLE
# -----------------------------
st.image("logo.png", width=150)

st.title("ASH Study Assistant")

st.write(
    "Ask me anything about your studies!"
)

# -----------------------------
# PDF UPLOAD
# -----------------------------
st.sidebar.header("📄 Study Material")

uploaded_file = st.sidebar.file_uploader(
    "Upload your university notes (PDF)",
    type=["pdf"]
)

pdf_text = ""

if uploaded_file is not None:

    pdf_reader = PdfReader(uploaded_file)

    for page in pdf_reader.pages:

        text = page.extract_text()

        if text:
            pdf_text += text + "\n"

    st.sidebar.success(
        f"✅ PDF loaded! {len(pdf_reader.pages)} pages found."
    )

# -----------------------------
# STUDY MODE
# -----------------------------
mode = st.selectbox(
    "Choose Study Mode",
    [
        "💬 Normal Chat",
        "📚 Explain Topic",
        "📝 Make Notes",
        "❓ Generate MCQs",
        "🎯 Exam Questions",
        "🎨 Generate Image"
    ]
)

# ============================================================
# IMAGE GENERATOR
# ============================================================

if mode == "🎨 Generate Image":

    st.header("🎨 AI Image Generator")

    st.write(
        "Describe the image you want and AI will create it."
    )

    image_prompt = st.text_area(
        "Describe your image",
        placeholder=(
            "Example: Create a simple educational diagram "
            "showing the water cycle with evaporation, "
            "condensation, precipitation and collection."
        ),
        height=120
    )

    if st.button(
        "🎨 Generate Image",
        use_container_width=True
    ):

        if not image_prompt.strip():

            st.warning(
                "Please describe the image you want."
            )

        else:

            with st.spinner(
                "🎨 Creating your image..."
            ):

                try:

                    image = image_client.text_to_image(
                        prompt=image_prompt,
                        model="black-forest-labs/FLUX.1-schnell"
                    )

                    st.image(
                        image,
                        caption="Generated by ASH Study Assistant",
                        use_container_width=True
                    )

                    image_bytes = BytesIO()

                    image.save(
                        image_bytes,
                        format="PNG"
                    )

                    image_bytes = image_bytes.getvalue()

                    st.download_button(
                        label="⬇️ Download Image",
                        data=image_bytes,
                        file_name="ash_study_image.png",
                        mime="image/png",
                        use_container_width=True
                    )

                except Exception as e:

                    st.error(
                        "❌ Image generation failed."
                    )

                    st.code(str(e))


# ============================================================
# NORMAL STUDY CHAT
# ============================================================

else:

    # -----------------------------
    # CHAT HISTORY
    # -----------------------------
    if "messages" not in st.session_state:

        st.session_state.messages = []

    for message in st.session_state.messages:

        with st.chat_message(message["role"]):

            st.markdown(
                message["content"]
            )

    # -----------------------------
    # TEXT INPUT
    # -----------------------------
    typed_prompt = st.chat_input(
        "Ask your study question..."
    )

    # -----------------------------
    # VOICE INPUT
    # -----------------------------
    st.subheader("🎤 Ask by Voice")

    audio_value = st.audio_input(
        "Record your question"
    )

    voice_prompt = None

    if audio_value is not None:

        with st.spinner(
            "🎧 Understanding your voice..."
        ):

            try:

                audio_file = client.files.upload(
                    file=audio_value,
                    config={
                        "mime_type": "audio/wav"
                    }
                )

                response = client.models.generate_content(
                    model="gemini-3.6-flash",
                    contents=[
                        audio_file,
                        """
                        Listen to the student's spoken question.

                        Convert the spoken question into text.

                        Return ONLY the student's question.
                        Do not answer the question.
                        """
                    ]
                )

                voice_prompt = response.text.strip()

                st.success(
                    "🎤 Voice question detected:"
                )

                st.write(
                    voice_prompt
                )

            except Exception as e:

                st.error(
                    "❌ Could not understand the recording."
                )

                st.code(
                    str(e)
                )

    # -----------------------------
    # CHOOSE TEXT OR VOICE
    # -----------------------------
    prompt = typed_prompt

    if voice_prompt:

        prompt = voice_prompt

    # -----------------------------
    # PROCESS QUESTION
    # -----------------------------
    if prompt:

        st.session_state.messages.append(
            {
                "role": "user",
                "content": prompt
            }
        )

        with st.chat_message("user"):

            st.markdown(prompt)

        # -----------------------------
        # STUDY MODE INSTRUCTIONS
        # -----------------------------
        instructions = {

            "💬 Normal Chat":
                "Answer the student's question clearly and accurately.",

            "📚 Explain Topic":
                "Explain the topic in extremely simple words. "
                "Use examples and step-by-step explanations.",

            "📝 Make Notes":
                "Convert the student's topic into short, "
                "easy-to-revise study notes with headings "
                "and bullet points.",

            "❓ Generate MCQs":
                "Create 10 important multiple-choice questions. "
                "Give four options and clearly identify the correct answer.",

            "🎯 Exam Questions":
                "Create important exam-style questions from this topic. "
                "Include both short and long questions."
        }

        # -----------------------------
        # PDF INSTRUCTIONS
        # -----------------------------
        if pdf_text:

            pdf_instructions = f"""
The student has uploaded university study material.

IMPORTANT:
- Use the uploaded PDF as the main source for your answer.
- Answer the student's question based on the PDF.
- If the answer is not available in the PDF, clearly say:
  "I couldn't find this information in your uploaded PDF."
- Do not invent information and pretend it came from the PDF.

UPLOADED PDF CONTENT:
--------------------
{pdf_text}
--------------------
"""

        else:

            pdf_instructions = """
No PDF has been uploaded.

Answer the student's question using your normal knowledge.
"""

        # -----------------------------
        # SYSTEM PROMPT
        # -----------------------------
        system_prompt = f"""
You are an AI Study Assistant.

Your goal is to help university students learn.

Study mode:
{instructions[mode]}

Rules:
- Use simple English.
- Explain difficult concepts step by step.
- Give examples whenever useful.
- Do not unnecessarily use complicated terminology.
- If the student asks for an exam answer, make it easy to memorize.

{pdf_instructions}
"""

        # -----------------------------
        # AI RESPONSE
        # -----------------------------
        with st.chat_message("assistant"):

            with st.spinner(
                "Thinking..."
            ):

                response = client.models.generate_content(
                    model="gemini-3.6-flash",
                    contents=(
                        system_prompt
                        + "\n\nStudent question:\n"
                        + prompt
                    )
                )

                answer = response.text

                st.markdown(answer)

        # -----------------------------
        # SAVE AI RESPONSE
        # -----------------------------
        st.session_state.messages.append(
            {
                "role": "assistant",
                "content": answer
            }
        )
```
